### ISSUE TITLE
[Suggestion]: Anvil Crafting

### ISSUE THREAD

**Issue by Lanse505** [xt9/InWorldCrafting#10]
So while looking through code for suggestions for #8 .
I found the "AnvilRepairEvent" which lets you modify a few things:
Itemstack "left"
Itemstack "right"
Itemstack "output"
float "breakChance"

![image](https://user-images.githubusercontent.com/1495068/53305321-892e6800-3880-11e9-8694-37d97f6a998e.png)

Might be something worth looking into supporting?
Might be a bit out of scope since it's not an in-world interaction.

**Comment by Lanse505** [comment]
Also as always if you want help/a PR just give me a poke and I'll try to set one up :P

**Comment by xt9** [comment]
Not really an In world interaction, more of a sideeffect from interacting with a GUI. Rejected.

**Comment by Lanse505** [comment]
That's what I guessed ;P
