### ISSUE TITLE
Crash when throwing 3rd stack of gravel into creosote

### ISSUE THREAD

**Issue by Hjaldar** [xt9/InWorldCrafting#13]
Crash log: https://gist.github.com/Hjaldar/ab91dbc4270a1e4166d8a7890ba8c46b

Crash seems to occur as the 3rd stack of gravel hits the creosote.

This occurred in your in-dev pack, v 0.2

Crash occurs on logging into the world again. Fixed world by editing out the creosote in MCEdit, then was able to reproduce the crash once more.

**Comment by xt9** [comment]
Fixed in 7fa17a1f7a437936183c7c269a50de84ca3ea8a4
