### ISSUE TITLE
Feature Request -- Shift + Right Click Crafting

### ISSUE THREAD

**Issue by RogueRaiden** [xt9/InWorldCrafting#16]
I would like to suggest adding Shift + Right Click crafting in-world. 
Example would be holding a stack of string, holding Shift then right clicking would use 4 string and craft a block of wool.

**Comment by xt9** [comment]
This isn't exactly inworld since the items never leave your inventory, and there already exists mods that can do compact crafting when you press a keybind while hovering a stack. Thanks for the suggestion but this won't be added.
