### ISSUE TITLE
Flowing liquid can't be consumed

### ISSUE THREAD

**Issue by lynaevm** [xt9/InWorldCrafting#23]
in Fluid to Item crafting, it recognizes flowing liquids as valid for the transformation.  This means that no recipe can be successfully set to consume the block since players can just toss it in the flowing liquid to avoid the cost.

**Comment by xt9** [comment]
If you set the consume flag to true it won't do the transformation in flowing liquids., and will always consume a source block
EDIT: This hasn't always been the case so be sure to update to the latest version.
