### ISSUE TITLE
Errors galore on startup when altering recipes

### ISSUE THREAD

**Issue by BigCasper** [xt9/InWorldCrafting#25]
The FluidtiItem won't take the IIngredient*n and multiples of the same IIngredient would load, but wouldn't work. (I know it's in documentation not to have duplicate ingredients). Logs throw out:
"[INITIALIZATION][CLIENT][ERROR] add.zs:30 > 3 methods available but none matches the parameters (ZenTypeNative: crafttweaker.item.IItemStack, ZenTypeNative: crafttweaker.liquid.ILiquidStack, any[], bool)
This is usually an error in your script, not in the mod
transform(ZenTypeNative: crafttweaker.item.IItemStack, ZenTypeNative: crafttweaker.liquid.ILiquidStack, ZenTypeNative: crafttweaker.item.IIngredient, bool)
transform(ZenTypeNative: crafttweaker.item.IItemStack, ZenTypeNative: crafttweaker.liquid.ILiquidStack, ZenTypeNative: crafttweaker.item.IIngredient)
transform(ZenTypeNative: crafttweaker.item.IItemStack, ZenTypeNative: crafttweaker.liquid.ILiquidStack, ZenTypeNative: crafttweaker.item.IItemStack)"

**Comment by TheDeviantCrafter** [comment]
Would you mind sharing the entire scrip file and your CraftTweaker.log file?

**Comment by BigCasper** [comment]
@TheDeviantCrafter
Logs: https://pastebin.com/vdRsaPzk
Script: https://pastebin.com/9gF9h7pb
3 other scripts are loading in at launch, but those are not causing problems.

**Comment by BigCasper** [comment]
@TheDeviantCrafter Any helpful insight yet?

**Comment by BigCasper** [comment]
Update: errors persist even when not using IIngredient like IItemStack (with multiplier).
Errors are the same, even with additional libraries imported for safety.
New code: https://pastebin.com/ghZySpD5
Same Errors, new log :https://pastebin.com/YpMK5WrP

**Comment by kindlich** [comment]
Since the code base and the methods shown in the error message are not the same, please tell on which version of the mod you are and try updating your mod version if possible?
