### ISSUE TITLE
FluidToItem doesn't work with "consumed = true"

### ISSUE THREAD

**Issue by ZigTheHedge** [xt9/InWorldCrafting#30]
No errors in crafttweaker, but when I use this script with modded liquid (Fluid Block extends BlockFluidFinite):

`FluidToItem.transform(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:cow"}}), <liquid:alivewater>, [<minecraft:egg>, <minecraft:wheat>], true);
`

it doesn't work at all (I don't get the resulting item), but if I omit the last argument:

`FluidToItem.transform(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:cow"}}), <liquid:alivewater>, [<minecraft:egg>, <minecraft:wheat>]);
`

it works fine, but the liquid doesn't get consumed of course.
If I change liquid to vanilla water - everything works as intended.
Forge: 2847
Mod version: 1.2.0

**Comment by xt9** [comment]
Consume will only work with source blocks, BlockFluidFinite is probably never considered a source block.
edit: Crafting in general will only work with sourceblocks.
