### ISSUE TITLE
Parameter Errors, Suggestion to change the Wiki

### ISSUE THREAD

**Issue by NerdySpider** [xt9/InWorldCrafting#31]
Hello, I am writing this to notify the creator of a possible mistype within the wiki or a change that caused the documentation to be slightly incorrect. 

When using []'s within item parameters, it comes up with errors, thanks to a discord member I was able to figure out how and why this happened.

This was my code:
(And yes, before asking, the import code was applied first as well. Also, 'wooda' is just a contenttweaker fluid.)

**mods.inworldcrafting.FluidToFluid.transform(<liquid:wooda>, <liquid:water>, [<rustic:grape_stem>]);;**

But, in making it, this error occurred. [Pastebin Link](https://pastebin.com/W4uFBCgq)

Thanks to a discord user, they found out that the []'s were causing this error, in some examples on the wiki, items are shown with this bracket, and on removing them:

**mods.inworldcrafting.FluidToFluid.transform(<liquid:wooda>, <liquid:water>, <rustic:grape_stem>);**

This error was fixed, I am not too sure if this is selective in my case, but if this exsists still with the current versions of craftttweaker: (CraftTweaker2-1.12-4.1.20.jar) Then this might want to be fixed within the wiki.

![image](https://user-images.githubusercontent.com/29170640/77218283-d3feda00-6b7d-11ea-84d3-87c10fcaf26a.png)

**Comment by xt9** [comment]
Make sure you're running InWorldCrafting version 1.2.0 which the wiki is updated for.
