### ISSUE TITLE
FluidToItem and FluidToFluid Can't have 2 items

### ISSUE THREAD

**Issue by SirJBiscuit** [xt9/InWorldCrafting#32]
FluidToItem And FluidToFluid Won't Accept 2 or more items inside of inworldcrafting Array, InWorldCrafting can only be used with <>.. doesn't work with [] brackets therefore can't use more than 1 item InWorld

Just wondering why it didn't work..

Script:
https://pastebin.com/AzMgSEpe

CraftTweaker Log:
https://pastebin.com/xpaYTpEf

- Thanks

**Comment by xt9** [comment]
Check that you're actually using InWorldCrafting version 1.2.0
