### ISSUE TITLE
can't resolve destablized redstone

### ISSUE THREAD

**Issue by mrstuffem** [xt9/InWorldCrafting#33]
im trying to change the recipe for the coils from thermal but, it keeps saying  ERROR: reception coil.zs:1: Could not resolve liquid : fluid_redstone
i think its because i have the id wrong but everywhere i look this is all i can find. ive tried using HWYLA and advanced tool tips with jei and they all lead to the same id.

here is the script im trying to use 
mods.inworldcrafting.FluidToItem.transform(<thermalfoundation:material:513>, <liquid:fluid_redstone>, [<minecraft:gold_ingot>]);

**Comment by mrstuffem** [comment]
through trial and error i found the true id is simply redstone so, you would use liquid:redstone

**Comment by xt9** [comment]
Thanks for updating the issue, I _think_ all modded liquids are prefixed with fluid_ in their registry id, but in crafttweaker you omit that part. So for example fluid_creosote would map to liquid:creosote. I think the best way to find out what name to use is to run `/ct fluids` or something like that.
