### ISSUE TITLE
Issue with using lava as fluid

### ISSUE THREAD

**Issue by pupnewfster** [xt9/InWorldCrafting#5]
I had two ideas so am just using the second one of them but figured I should report this as not working anyways.

With version 0.13.0 trying to do FluidToItem transforms do not work if the fluid is lava. The item lights on fire and bounces out of the lava in its original state. (Happens when consume is true and false.)

**Comment by xt9** [comment]
Yep, this is the intended behaviour as the items need to be fully submerged for the craft to complete.
