### ISSUE TITLE
Issue with Fluid to Item

### ISSUE THREAD

**Issue by marianyp** [xt9/InWorldCrafting#6]
There seems to be an issue with Fluid to Item. I have the consume parameter set to true, and when I put my input item inside the source fluid then the gets consumed, which is how it's supposed to work. However, when I put an item inside of a fluid that ISN'T the source fluid (the flowing fluid), the item still converts, but the fluid isn't consumed.

[Example of the issue](https://imgur.com/a/E8nbafP)

Here's my script.

```
import mods.inworldcrafting.FluidToItem;
import mods.inworldcrafting.FluidToFluid;

FluidToItem.transform(<contenttweaker:charged_wart_item>, <liquid:liquid_xp>, <minecraft:nether_wart>, true);
FluidToFluid.transform(<liquid:liquid_xp>, <liquid:water>, <minecraft:experience_bottle>, true);
```

What I was **hoping** to happen is **FluidToItem would only work if it's the source fluid**.
FluidToFluid handles this right. If you put the input item in a flowing fluid instead of a source fluid then no conversion happens.

**Comment by xt9** [comment]
I like what you're trying to do here, looks cool. 👍 
I'm aware of the issue and it should be fixed if you update to the latest version. Let me know if that's not the case.
